
name: DoxFX -> Documentation generator

on:
  push:
    branches: [ release ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      
      - uses: nikeee/docfx-action@v1.0.0
        with:
          args:  docfx/docfx.json --build --overwrite --output ./public

      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.6.4
        with:
          personal_token: ${{ secrets.GH_PAT }}
          publish_dir: ./public/_site

